### ISSUE TITLE
Package missing error occured in i.mx8 Processor board

### ISSUE THREAD

**Issue by bharathpoojary** [SiliconLabs/wisun-br-linux#14]
Hello,

I have tried the  WI-sun border router setup example in NXP [i.mx](https://i.mx/) processor board instead of raspberry pi.

i have successfully created and installed Linux OS on [i.mx](https://i.mx/) using Yocto project.but while compiling wisun source code I'm getting the error for few packages which i have mentioned below.can anyone please help me on this issue?

![Screenshot from 2024-04-17 11-42-17](https://github.com/SiliconLabs/wisun-br-linux/assets/34151850/da076ddd-703b-4a6a-bfd2-64e199eaf682)

thank you

**Comment by MathisMARION** [comment]
Hello,

Your system seems to be missing [`libnl`](https://github.com/thom311/libnl). It is listed as dependency in the main [`README`](https://github.com/SiliconLabs/wisun-br-linux?tab=readme-ov-file#compiling).

**Comment by jerome-pouiller** [comment]
@bharathpoojary I assume @MathisMARION's answer solved your issue. Re-open the issue if I am wrong.
