### ISSUE TITLE
ipv6_prefix from wsbrd command line

### ISSUE THREAD

**Issue by silabs-TamasSz** [SiliconLabs/wisun-br-linux#2]
Starting `wsbrd` but not specifying the config file (with `-F`) result in the message:
```txt
You must specify a ipv6_prefix
```
However it seems there is no option to specify IPv6 prefix in the command line.

**Comment by silabs-JulienT** [comment]
The ipv6_prefix can be configured through the configuration file (ipv6_prefix option).

**Comment by jerome-pouiller** [comment]
Note that you can use `-o ipv6_prefix=xxxx`
