### ISSUE TITLE
Require step/procedure for Cross Compilation

### ISSUE THREAD

**Issue by krunalchauhan637** [SiliconLabs/wisun-br-linux#3]
Want to integrate wisun-br-linux in RB-i.MX 6UL.
![Capture (1)](https://user-images.githubusercontent.com/59273222/166872010-df9ea134-1b7b-46af-b0de-68f3d8c073f2.PNG)

Can I know procedure or step to intrgrate wisun-br-linux ?

If any details require from our end let me know

**Comment by krunalchauhan637** [comment]
Is there any positive update ?

**Comment by MarcDorval** [comment]
Hi,

Did you follow [the readme](https://github.com/SiliconLabs/wisun-br-linux/blob/main/README.md)?
How far have you been in this?

Regards,
Marc

**Comment by krunalchauhan637** [comment]
Yes, I have gone through It. 
But I did not get idea.

Can you help me out ?

**Comment by jerome-pouiller** [comment]
It seems you are using Yocto. Refer to the Yocto documentation to know how to create recipes (I think that inheriting from `cmake` should be sufficient).

**Comment by krunalchauhan637** [comment]
Can  I know cross compilation steps ?

**Comment by jerome-pouiller** [comment]
`wsbrd` cross-compiles as usual cmake projects, using `--toolchain` argument. Check out `cmake.bbclass` in your Yocto distribution for more information.

**Comment by krunalchauhan637** [comment]
Thanks for guidance.
I have some progress on cross compilation.
I have write my own makefile to compile wsbrd.

Further I need required network link library source code to cross compile. 
![Screenshot from 2022-06-02 11-18-49](https://user-images.githubusercontent.com/59273222/171561657-c702d161-d303-4a38-97bb-480e2136548c.png)

**Comment by jerome-pouiller** [comment]
I have googled it for you. Refer to this documentation: https://www.phytec.eu/products/software/yocto/phytec-unified-yocto-bsp-release/ which refer to this one: https://www.yoctoproject.org/docs/2.4.2/yocto-project-qs/yocto-project-qs.html

**Comment by krunalchauhan637** [comment]
@jerome-pouiller 
Thanks for quick reply. 
I am directly cross compile using makefile.

I have cross compile mbedtls 3.0.0 Library & integrate.
Same thing also done for pcap & systemd.

But I cant find proper network link library source code.


[Makefile.txt](https://github.com/SiliconLabs/wisun-br-linux/files/8822751/Makefile.txt)

**Comment by jerome-pouiller** [comment]
I have to enable `libnl` in your BSP.

**Comment by jerome-pouiller** [comment]
BTW, I still suggest the use of the Yoco official recipes to cross-compile.

**Comment by krunalchauhan637** [comment]
Okay. Do you think that will work with minimal changes ?

**Comment by jerome-pouiller** [comment]
You can try to hack `tun.c`, but I can't guarantee the result.

**Comment by krunalchauhan637** [comment]
Thats what I am saying. 
I need to confirm that, If I go with Yoco official recipes to cross-compile.
Will it work for phytec board or that have also dependency ?
Becuase we are plan this board as production.

**Comment by jerome-pouiller** [comment]
`libnl` is a part of [`openembedded-core`][1] and has no exotic dependencies. If your recipe depends on `libnl`, everything will build straight right.

[1]: http://cgit.openembedded.org/openembedded-core/tree/meta/recipes-support/libnl/libnl_3.2.28.bb?h=morty

**Comment by krunalchauhan637** [comment]
Yes. I think It's better to go with yocto reicipe. Thanks for it.
Will check and share result

**Comment by krunalchauhan637** [comment]
Just want to know 
Are you compile and run application in which board ? 
On Same board ?

**Comment by jerome-pouiller** [comment]
Compile `wsbrd` on your host through Yocto. Then, you can run it on your Phytec board.

Sorry to be a bit harsh in my answers, but this issue is not related to `wsbrd`. I think you will get better answers if you ask to your board vendor (Phytec).

**Comment by krunalchauhan637** [comment]
@jerome-pouiller 
Not an issue. Thank you for your support.
