### ISSUE TITLE
question: Is the wisun protocol are public?

### ISSUE THREAD

**Issue by qianfan-Zhao** [SiliconLabs/wisun-br-linux#9]
Hi:

I am reading the wisun-br-linux code these days, and I can not find any IEs about wisun protocol defined in 802.15.4-2020 spec. Reference this code:

https://github.com/SiliconLabs/wisun-br-linux/blob/4cbabbab288354cdbeba12c831e20d518c698f34/stack/source/6lowpan/ws/ws_ie_lib.h#L35C34-L35C34

there has a document named as <<Wi-SUN Assigned Value Registry 0v24>> but I can not find it anywhere. 

So does the document is public and may I read it?

**Comment by silabs-ThibautC** [comment]
Hi,

Unfortunately, it is reserved for Wi-SUN alliance member's eyes. 

See the [membership benefits](https://wi-sun.org/membership-benefits/) page of wi-sun.org.

Thibaut

**Comment by qianfan-Zhao** [comment]
Thanks, since the document is unavaliable for me. I will close this issue.
